services:

  neo4j:
    #image: registry.gitlab.com/dbishagen/unibench-ind-data-generator/neo4j:5.25.1-unibench-${DATA_SIZE:-0.0}
    image: ghcr.io/dbishagen/neo4j:5.25.1-unibench-${DATA_SIZE:-0.0}
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
  

  mongodb:
    #image: registry.gitlab.com/dbishagen/unibench-ind-data-generator/mongo:8.0.0-rc11-jammy-unibench-${DATA_SIZE:-0.0}
    image: ghcr.io/dbishagen/mongo:8.0.0-rc11-jammy-unibench-${DATA_SIZE:-0.0}
    ports:
      - "27017:27017"


  # mysql:
  #   #image: registry.gitlab.com/dbishagen/unibench-ind-data-generator/mysql:9.1.0-unibench-${DATA_SIZE:-0.0}
  #   image: ghcr.io/dbishagen/mysql:9.1.0-unibench-${DATA_SIZE:-0.0}
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  

  postgres:
    #image: registry.gitlab.com/dbishagen/unibench-ind-data-generator/postgres:17.1-unibench-${DATA_SIZE:-0.0}
    image: ghcr.io/dbishagen/postgres:17.1-unibench-${DATA_SIZE:-0.0}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
